ports:
  - port: 3000
tasks:
  # - before: if [[ -z "$experiment" ]]; then cd playground/1st-proof-of-concept; else cd playground/$experiment; fi
    # command: nvm install 13.3.0 && npm install && npm start
  - before: cd playground/_mendel/
    command: nvm install 13.3.0 && npm install && nvm install node && npm install bootstrap && npx nodemon